name: 'Build filters list'
author: 'PiQuark6046 and contributors'
description: 'Builds the filters list'

inputs:
  filterslistname:
    description: 'The name of the filters list to build'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install npm packages
      run: |
        npm i
      shell: bash
      working-directory: ${{ github.action_path }}
    - name: Run program
      env:
        GITHUB_TOKEN: ${{ github.token }}
        FILTERSLISTNAME: ${{ inputs.filterslistname }}
        CI_WORKSPACE_PATH: ${{ github.workspace }}
        CI_ACTION_PATH: ${{ github.action_path }}
      run: |
        npm run ci -- --gh-token "$GITHUB_TOKEN" --filterslistname "$FILTERSLISTNAME" --ci-workspace-path "$CI_WORKSPACE_PATH" --ci-action-path "$CI_ACTION_PATH"
      shell: bash
      working-directory: ${{ github.action_path }}
